//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        public string maban { get; set; }
        public string makv { get; set; }
        public string tenban { get; set; }
        public string thuoctinh { get; set; }
    
        public virtual KHUVUC KHUVUC { get; set; }
    }
}
