//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALAMVIEC
    {
        public string maca { get; set; }
        public string manv { get; set; }
        public Nullable<System.TimeSpan> giobd { get; set; }
        public Nullable<System.TimeSpan> giokt { get; set; }
        public Nullable<decimal> sotien { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
