//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public string mahd { get; set; }
        public string mahh { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual HANGHOA HANGHOA { get; set; }
    }
}
