//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUNGCAP
    {
        public string mahh { get; set; }
        public string mancc { get; set; }
        public System.DateTime ngaynhap { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> gianhap { get; set; }
    
        public virtual HANGHOA HANGHOA { get; set; }
        public virtual NHACC NHACC { get; set; }
    }
}
