//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStoreApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public KHACHHANG()
        //{
        //    this.HOADONs = new HashSet<HOADON>();
        //}
    
        public string makh { get; set; }
        public string tenkh { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string maloaikh { get; set; }
        public Nullable<int> diemtichluy { get; set; }
    
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<HOADON> HOADONs { get; set; }
        //public virtual LOAIKHACHHANG LOAIKHACHHANG { get; set; }
    }
}
